name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: phpunit

      - name: Install dependencies
        run: composer install --no-suggest --prefer-dist -n -o

      - name: Run tests
        run: phpunit

  code-style:
    runs-on: ubuntu-latest

    name: Code Style Check

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: phpcs

      - name: Install dependencies
        run: composer install --no-suggest --prefer-dist -n -o

      - name: Run tests
        run: phpcs
